config/routes.rb
MusicApp::Application.routes.draw do
  resources :users
  resource :session, :except => [:edit, :update, :show]
  
  resources :bands do
    member do
      resources :albums, :only => [:index, :new, :create]
    end
  end
  resources :albums, :only => [:show, :edit, :update, :destroy] do
    member do
      resources :tracks, :only => [:index, :new, :create]
    end
  end
  resources :tracks, :only => [:show, :edit, :update, :destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :band_id
  
  validates :title, :band_id, :presence => true
  
  belongs_to(
    :band,
    :primary_key => :id,
    :foreign_key => :band_id,
    :class_name => "Band"
  )
  
  has_many(
    :tracks,
    :primary_key => :id,
    :foreign_key => :album_id,
    :class_name => "Track",
    :dependent => :destroy
  )
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  
  validates :name, :uniqueness => true
  validates :name, :presence => true
  
  has_many(
    :albums,
    :primary_key => :id,
    :foreign_key => :band_id,
    :class_name => "Album",
    :dependent => :destroy
  )
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title, :album_id, :lyrics, :type
  
  belongs_to(
    :album,
    :primary_key => :id,
    :foreign_key => :album_id,
    :class_name => "Album"
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :session_token, :password
  attr_reader :password
  
  before_validation :ensure_session_token
  
  validates :email, :uniqueness => true
  validates :email, :session_token, :presence => true
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 5, :allow_nil => true }
  
  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
    # write_attribute(:password_digest, BCrypt::Password.create(secret))
  end
  
  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end
  
   def self.generate_session_token
    SecureRandom.base64.html_safe
  end
  
  def self.find_by_credentials(email, secret)
    u = User.find_by_email(email)
    (u && u.is_password?(secret)) ? u : nil
  end 
    
  private 
  def ensure_session_token
  if self.session_token.nil?
    self.session_token = User.generate_session_token
  end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.where(:band_id => params[:id])
    @band = Band.find_by_id(params[:id])
    render :index
  end
  
  def show
    @album = Album.find_by_id(params[:id])
    @band = Band.find_by_id(@album.band_id)
    render :show
  end
  
  def new
    render :new
  end
  
  def create
    @album = Album.create(params[:album])
    @album.band_id = params[:id]
    if @album.save!
      flash[:message] = "Successfully created album #{@album.title}"
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end
  
  def edit
    @album = Album.find_by_id(params[:id])
    render :edit
  end
  
  def update
    @album = Album.find_by_id(params[:id])
    @album.update_attributes(params[:album])
    if @album.save!
      flash[:message] = "Successfully edited album #{@album.title}"
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @album = Album.find_by_id(params[:id])
    @album_title = @album.title
    @album.delete
    if @album.save!
      flash[:message] = "Successfully deleted album #{@album_title}."
      redirect_to albums_url
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end
  
  def show
    @band = Band.find_by_id(params[:id])
    render :show
  end
  
  def new
    render :new
  end
  
  def create
    @band = Band.create(params[:band])
    if @band.save!
      flash[:message] = "Successfully created band #{@band.name}"
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end
  
  def edit
    @band = Band.find_by_id(params[:id])
    render :edit
  end
  
  def update
    @band = Band.find_by_id(params[:id])
    @band.update_attributes(params[:band])
    if @band.save!
      flash[:message] = "Successfully edited band #{@band.name}"
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @band = Band.find_by_id(params[:id])
    @band_name = @band.name
    @band.delete
    if @band.save!
      flash[:message] = "Successfully deleted band #{@band_name}."
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
    end
      
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    email = params[:user][:email]
    secret = params[:user][:password]
    @user = User.find_by_credentials(email, secret)
    if @user
      log_in_user!(@user)
      flash[:message] = "Successfully logged in as user #{@user.id}"
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid email or password"]
      render :new
    end
  end
  
  def new
    render :new
  end
  
  def destroy
    @user = current_user
    logout!(@user)
    redirect_to user_url(@user)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    render :index
  end
  
  def show
  end
  
  def new
  end
  
  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:message] = "Successfully created user #{@user.id}"
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find_by_id(params[:id])
    render :show
  end
  
  def index
    @users = User.all
    render :json => @users
  end
  
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionHelper
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
  
  def logout!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end
  
  def current_user
    User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/track_helper.rb
module TrackHelper
end

app/views/albums/_form.html.erb
<% if action == :new %>
	<% message = "Create an album"%>
	<% action_url = albums_url %>
<% else %>
	<% message = "Edit album #{album.title}"%>
	<% action_url = album_url %>
<% end %>

<h1><%= message %></h1>

<form action="<%= action_url %>" method="POST">
    <% if action == :edit %>
       <input type="hidden" name="_method" value="put">
     <% end %>
	<input
	   name="authenticity_token"
	   type="hidden"
	   value="<%= form_authenticity_token %>">
   
   <label 
	   for="album_title">
	   Title
   </label>
   <input type="text" 
	   name="album[title]" 
	   id="album_title">
   <br />

   <input type="submit" value="submit">
</form>

app/views/albums/edit.html.erb
<%= render "form", :action => :edit, :album => @album %>

app/views/albums/index.html.erb
<h1><%= @band.name %>'s Albums</h1>
<% unless @albums.nil? %>
	<ul>
	<% @albums.each do |album| %>
		<li>
			<%= link_to(album.title, album_url(album)) %>
		</li>
	<% end %>
	</ul>
<% end %>

<%= link_to("Add album", new_album_url) %>

app/views/albums/new.html.erb
<%= render "form", :action => :new, :album => nil %>

app/views/albums/show.html.erb
<% if @album.nil? %>
	<p> No album <%= params[:id] %>. </p>
<% else %>
	<h1><%= @album.title %></h1>
	by
	<%= link_to(@band.name, band_url(@band)) %>
	<br />
	<%= link_to("Edit album", edit_album_url(@album)) %>
<% end %>

app/views/bands/_form.html.erb
<% if action == :new %>
	<% message = "Create a band "%>
	<% action_url = bands_url %>
<% else %>
	<% message = "Edit band #{band.name}"%>
	<% action_url = band_url %>
<% end %>

<h1><%= message %></h1>

<form action="<%= action_url %>" method="POST">
    <% if action == :edit %>
       <input type="hidden" name="_method" value="put">
     <% end %>
	<input
	   name="authenticity_token"
	   type="hidden"
	   value="<%= form_authenticity_token %>">
   
   <label 
	   for="band_name">
	   Name
   </label>
   <input type="text" 
	   name="band[name]" 
	   id="band_name">
   <br />

   <input type="submit" value="submit">
</form>

app/views/bands/edit.html.erb
<%= render "form", :action => :edit, :band => @band %>

app/views/bands/index.html.erb
<h1>Bands</h1>
<% unless @bands.nil? %>
	<ul>
	<% @bands.each do |band| %>
		<li>
			<%= link_to(band.name, band_url(band)) %>
		</li>
	<% end %>
	</ul>
<% end %>

<%= link_to("Create new band", new_band_url) %>

app/views/bands/new.html.erb
<%= render "form", :action => :new, :band => @band %>

app/views/bands/show.html.erb
<% if @band.nil? %>
	<p> No band <%= params[:id] %>. </p>
<% else %>
	<h1> <%= @band.name %> </h1>

	<%= link_to("Albums", albums_url) %>
	<br />
	<br />
	
	<%= link_to("Edit band", edit_band_url(@band)) %>
	<%= button_to("Remove band", band_url, :method => :delete) %>
<% end %>

<br />
<%= link_to("Bands", bands_url) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:message]%>
	<p class="message">
		<%= flash[:message]%>
	</p>
	<% end %>
	
	<% if flash[:errors]%>
	<p class="errors"> 
		<h2>Errors:</h2>
		<ul>
		<% flash[:errors].each do |error|%>
		<li>
			<%= error %>
		</li>
		<% end %>
		</ul>
	</p>
	<% end %>
	
	<% if logged_in? %>
		<%= button_to("Log out", session_url, :method => :delete) %>
	<% else %>
		<%= link_to("Log In", new_session_url) %>
		<%= link_to("Sign Up", new_user_url) %>
	<% end %>
	

<%= yield %>

</body>
</html>

app/views/tracks/index.html.erb
<h1>Tracks</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
	<input
	   name="authenticity_token"
	   type="hidden"
	   value="<%= form_authenticity_token %>">
	   
   <label 
	   for="user_email">
	   Email
   </label>
   <input type="text" 
	   name="user[email]" 
	   id="user_email">
   <br />
   
   <label 
	   for="user_password">
	   Password
   </label>
   <input type="password" 
	   name="user[password]" 
	   id="user_password">
   <br />
   
   <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<% if @user.nil? %>
	<p> No user <%= params[:id] %>. </p>
<% else %>
	<h1>User <%= @user.id %> </h1>
	<p> <%= @user.email %> </p>
<% end %>